### ISSUE TITLE
Final checks vs PLOSone 

### ISSUE THREAD

**Issue by MengLeZhang** [MengLeZhang/crimeMaps-preReg-code#8]
- [x] Check review reply letter and tracked changes. 

- [x] Please ensure that your manuscript meets PLOS ONE's style requirements, including those for file naming. The PLOS ONE style templates can be found at https://journals.plos.org/plosone/s/file?id=wjVg/PLOSOne_formatting_sample_main_body.pdf and https://journals.plos.org/plosone/s/file?id=ba62/PLOSOne_formatting_sample_title_authors_affiliations.pdf
- [x] Final check to add access dates and dates to newspaper artciles to  .docx submission
-

**Comment by MengLeZhang** [comment]
From MA review: 
- [ ]    Please, check each of the Word documents, as there is at least one edit made to it. (check emails data ~ end of Aug 2022)
- [x]    I changed the name of the main Word document from ‘project protocol-v0.0.12.doc’ to ‘Manuscript_cleaned.doc’. I think it is better this way.
- [x]    There is only Figure 1 and 2 in the main manuscript. But you mentioned Figure 3 in the response to reviewer which can’t be found.
- [x]    The key edit is consistency with the word ‘snap-points’, ‘Snap points’, ‘snap points’, etc. So, I chose ‘snap-points’.
- [x]    The figures still needs editing. The texts on the figures are not big enough! Can you send me the codes for plotting figure 1
- [x]    Based on the referenced plosone article, figure labelling and referencing utilizes ‘Fig *’ rather than ‘Figure *’.
- [x] Also, to differentiate ‘Fig 1’ in the main manuscipt from say ‘Fig 1’ in supplement S1, I adopt the format ‘Fig S1.1’ for the latter.

- [x] As much as we want to emphasize that reviewer 2 get the idea of ‘study protocol’ wrong, it is advisable for us to soften our response a little bit more.     
- [x]   In the main manuscript, you reference figure 7 from another paper. We cannot reference an item from within another paper. Just referencing the paper is enough.
- [x]     Please, allow me to re-draw Fig 2 from the main manuscript and Fig S2.1 from supplement S2. I will send them to you shortly.

Merged changes from MAnalytics to response to reviews

**Comment by MengLeZhang** [comment]
@MAnalytics  Incorporated all the changes to the raw MD files. Changed the figures that were wrong/ to look better. Will build final .docx files tomorrow and go through correcting things.

**Comment by MAnalytics** [comment]
@MengLeZhang Thank you very much for all your efforts. Greatly appreciated!
